name: Test & Deploy
on:
  schedule:
    - cron: '0 8 * * 1' # M H d m w (Mondays at 8:00)
  push:
    tags: ['v*']
  pull_request_target:
  workflow_dispatch:
jobs:
  authorize:
    environment:
      ${{ (github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository) &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ✓
  packages:
    needs: [authorize]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run:
          npm ${{ github.event_name == 'push' && 'publish' || 'publish
          --dry-run' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: install ldid
        run: |
          sudo apt install --yes libplist-dev
          git clone --branch v2.1.5 git://git.saurik.com/ldid.git 
          sudo g++ -pipe -o /usr/bin/ldid ldid/ldid.cpp -I. -x c ldid/{lookup2.c,sha1.h} -lplist -lcrypto
      - uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      - id: build
        name: build
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
          cp node_modules/@npcz/magic/dist/magic.mgc assets/magic.mgc
          npx --yes pkg --no-bytecode --public-packages "*" --public package.json
          rm assets/magic.mgc
          for cmd in '' runner publish pr; do
            build/cml-linux-x64 $cmd --version
          done
          cp build/cml-linux{-x64,}
          cp build/cml-macos{-x64,}
